<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Title>LoadingIndicators.Avalonia</Title>
    <Version>0.0.0</Version>
    <Authors>Der_Floh</Authors>
    <Description>A collection of loading indicators for Avalonia.</Description>
    <PackageProjectUrl>https://github.com/Der-Floh/LoadingIndicators.Avalonia</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Der-Floh/LoadingIndicators.Avalonia</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Avalonia;Avalonia-UI;Loading-Animation;Loading-Spinner;Loading-Indicator;Loading;Animation</PackageTags>
    <PackageId>LoadingIndicators.Avalonia.New</PackageId>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\icon.png" Pack="true" PackagePath="\" />
    <None Include="..\LICENSE" Pack="true" PackagePath="\" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="[11.1.0,12.0.0)" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
    <PackageReference Include="Avalonia" Version="[12.0.0,)" Condition="'$(TargetFramework)' == 'net8.0'" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.300">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>