name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    uses: Der-Floh/Der-Floh/.github/workflows/app-pages.yml@v1
    with:
      project-path: LoadingIndicators.Avalonia.Demo/LoadingIndicators.Avalonia.Demo.Browser/LoadingIndicators.Avalonia.Demo.Browser.csproj
      stamp-version: false
